---
title: "Index"
output: html_document
---

# Course Objectives

1. To give participants the confidence and skills to produce publication-quality outputs from their research.
2. To build participants' capabilities and professionalism in using R for reproducible research.
3. Promoting the use of spatial methods by participants, in line with CEPESP's core strengths.
3. Improving teamwork within CEPESP by ensuring the shared skills and language for conducting intensive research.

# Audience
Anyone associated with CEPESP who wants to produce precise, attractive tables, charts, maps and documents. For example, to quickly take the results of multiple regressions and present them in formatted tables; to create marginal effect plots or histograms; to analyze and generate maps of key datasets; or to produce an entire reproducible article. 

# Logistics

The course will take place in 4000 C+D, in the Economics building, at 8am-10am weekly, for 10 weeks starting on March 20th. Participants will use their own laptop where possible. The format will start with a demonstration of key functionality, followed by an exercise to be conducted in class, and concluding with a short summary. There is no homework, but participants will be guided to key reference texts, tutorials and examples where they can learn more and practice.

Participants will be asked to prepare their laptops before the first class (install Rstudio, latex, key packages).

# Weekly Activities

1. **Introduction** (20/03) - Explain the Rstudio interface, options and workflow. Importing data. Viewing data. R as a calculator. R chunks. Text and equations. Basic formatting. Producing PDFs and web pages from markdown.

2. **Playing with Data** (27/03) - Dataframe manipulation. Piping. Object types.

3. **Describing Data** (03/04) - Descriptive statistics, t-tests. Further data manipulation. Table outputs (kable).

4. **Regressions with Data** (10/04) - Models. Stargazer. Chunk options.

5. **Charts from Data** (17/04) - Charts in ggplot. Scatterplots, histograms. Marginal effect plots. Colours.

6. **Combining Data** (24/04) - Merging data. Conditional data manipulation. 

7. **Analysing Data** (08/05) - Performing a Comprehensive Analysis.

8. **Mapping Data 1** (15/05) - Spatial analysis basics - formats, CRS, SF. Plotting maps. Palettes.

9. **Mapping Data 2** (22/05) - Georeferencing, spatial statistics, raster data.

10. **Interactive Data** (29/05) - Interactive applications - shiny. 

