---
title: "Outline Spatial Analysis in R"
author: "JP"
date: "April 6, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(knitr)

#First annoying thing is the need to install the development version of ggplot2 so we can plot simple features
#devtools::install_github("tidyverse/ggplot2")
library(ggplot2)

#And install other packages
library(sf)
library(leaflet)
#[sp, maptools, rgdal, rgeos etc. if not auto-loaded by above]

#Emphasize one type of object, "sf", regardless of point/line/polygon type.
#Show how sf stores the geometry in an extra column in the data.frame
```

```{r}
#Opening a shapefile
sf <- st_read("Brazil_s.shp",stringsAsFactors = FALSE)

#Or converting a list of coordinates from a data.frame to a simple features object
sf2 <- df %>% st_as_sf(coords = c("longitude", "latitude"), 
                 crs = 4326, relation_to_geometry = "field")

#Changing the projection
sf <- sf %>% st_transform(4326) #Works with epsg codes
sf <- sf %>% st_transform("+proj=longlat +datum=WGS84")
sf <- sf %>% st_transform("+proj=utm +datum=WGS84 +zone=45")
sf <- sf %>% st_transform("+proj=longlat +ellps=GRS80 +no_defs")
```

```{r}
#Normal tidyverse data manipulation works with sf
sf <- sf %>% mutate(Double_Area=Shape_Area*2)
sf <- sf %>% separate(CD_GEOCODM,into=c("State","Mun"),sep=2, remove=FALSE) %>% filter(State==26)
```

```{r}
#Plotting with ggplot2
sf %>% ggplot() + 
  geom_sf()

sf %>% ggplot() + 
  geom_sf(aes(fill=Shape_Area))

sf %>% ggplot() + 
  geom_sf(aes(fill=Shape_Area)) +
  theme_classic() +
  coord_sf(datum=NA)
```

```{r}
#Interactive Maps to use in HTML outputs - Leaflet/Mapview
library(leaflet)
library(mapview)

sf %>% mapview()

sf %>% mapview(zcol="Shape_Area", legend=TRUE)
```

```{r}
library(cepespR)
#Download and prepare some cepesp data...(one observation per municipality so we can merge it in)
data <- cepespdata(year=2014, position="Governor", regional_aggregation="Municipality",political_aggregation="Candidate",state="PE")

data <- data %>%
  group_by(COD_MUN_IBGE) %>%
  mutate(Vote_Pct=(QTDE_VOTOS/sum(QTDE_VOTOS))*100) %>%
  ungroup() %>%
  filter(NOME_URNA_CANDIDATO=="PAULO CÂMARA")

#Merging in data into a shapefile is the same as normal
sf_merged <- sf %>% rename("COD_MUN_IBGE"="CD_GEOCODM") %>% 
  mutate(COD_MUN_IBGE=as.numeric(COD_MUN_IBGE)) %>%
  left_join(data,by="COD_MUN_IBGE")

#Now we can map eg. 
sf_merged %>%
  ggplot() +
  geom_sf(aes(fill=Vote_Pct)) +
  theme_classic() +
  coord_sf(datum=NA)

```

```{r}
#Spatial operators
sf %>% st_length()
sf %>% st_area()

sf %>% st_intersection(sf2)
sf %>% st_union(sf2)
sf %>% st_distance(sf2) #Distance matrix for points
```

```{r}
#Some special visualization techniques that change the representation of polygons

#Cartograms - area of polygon proportional to variable. Seems to work best with different projection
#devtools::install_github("sjewo/cartogram")
library(cartogram)
sf_cart <- sf_merged  %>% st_transform("+proj=utm +datum=WGS84 +zone=45") %>% cartogram("Vote_Pct", itermax=3)

sf_cart %>% ggplot() + 
  geom_sf() + 
  theme_classic() + 
  coord_sf(datum=NA)

#Equal Area Cartograms - Hexmaps
#devtools::install_github("jbaileyh/geogrid")
library(geogrid)

sf_hex_grid <- sf_merged %>% calculate_grid(grid_type="hexagonal")
sf_hex_grid <- sf_merged %>% assign_polygons(sf_hex_grid)

sf_hex_grid %>% st_as_sf() %>% ggplot() +
  geom_sf(aes(fill=Vote_Pct)) + 
  geom_text(aes(x=V1,y=V2,label=substr(NM_MUNICIP,1,2)),size=2,col="white") +
  theme_classic() + 
  coord_sf(datum=NA) + 
  xlab("") +
  ylab("")
```

```{r}
#Spatial Statistics - Moran's I
library(spdep)

#Three steps:
#1. Identify neighbours - NB: queen=TRUE specifies queen contiguities instead of rook contiguities.
neighbours <- sf_merged %>% as("Spatial") %>% poly2nb(queen=TRUE)

#2. Create neighbour weights - NB: style="W" here relates to row standardised weights
neighbours_weights <- neighbours %>% nb2listw(style="W")

#3. Calculate Moran's I
sf_merged %>% pull(Vote_Pct) %>% moran(neighbours_weights,length(neighbours),Szero(neighbours_weights))

```

```{r}
#Sub-setting data is the same as in the tidyverse:

#Select SP city 
sf_SP <- sf_merged %>% filter(COD_MUN_IBGE==3550308)

sf_SP %>% ggplot() +
  geom_sf()
```

```{r}
#Transforming between data types:x

#1. Polygons to Points
sf_points <- sf %>% st_centroid()

sf_points %>% ggplot() + 
  geom_sf()

#2. Points to Polygons (Voronoi)

library(dismo)
sf_voronoi <- sf_points %>% 
  as("Spatial") %>% 
  voronoi() %>% 
  st_as_sf() %>% 
  st_intersection(sf) 

sf_voronoi %>% ggplot() + 
  geom_sf() + 
  theme_classic() +
  coord_sf(datum=NA) #not perfect

#3. Points to Raster - Inverse Distance Weighting

library(gstat)
sf_points_sp <- sf_points %>% as("Spatial")
grid <- st_make_grid(sf_points,n=200,what="corners") %>% as("Spatial")

#Where 'Shape_Area' is the variable you want to interpolate:
idw_sf <- idw(Shape_Area~1,locations=sf_points_sp,newdata=grid) %>% 
  st_as_sf() 

idw_sf %>%
  cbind(st_coordinates(idw_sf)) %>%
  ggplot() +
  geom_tile(aes(x=X,y=Y,fill=var1.pred))

```

